// Hardware names stay generation-specific; the shared actions are deliberately
// reused only where the two source chapters describe the same behavior.
const pushAtlas=(()=>{
  function controller(n){
    const chapter='using-push-'+n,p=manualCompletion.make(chapter),two=n===2,
      layout=two?'Layout':'Note',pref=two?'Setup':'hold User';
    const detail=(anchor,label,body,terms=[])=>p(anchor,label,body,[],terms);
    const connect=p(chapter,'Connect','Push '+n+' controls the connected Live Set; Note mode plays or sequences, while Session mode launches clips.',[],[], '',[
      p('setup','Plug in',two?'Connect the supplied power adapter and USB cable, then turn Push on at the rear power button.':'Connect Push by USB with Live running.',[],[['Detection','Live normally recognizes the controller without a separate driver or manual control-surface setup.'],...(two?[['Firmware','Live updates can include firmware. Follow the device’s update prompts after updating Live.']]:[])]),
      p('browsing-and-loading-sounds','Browse / load','Press Browse. The selected device determines whether you are replacing an instrument, an effect, or a drum-pad sound.',two?[
        'Turn the encoders or use the arrows to move through columns; the rightmost upper display buttons move in the folder hierarchy.','Use Preview to audition. Shift + Master encoder adjusts preview level. Press Load to replace the selected item.'
      ]:[
        'Use the Selection buttons to move up a column and State buttons to move down. Encoders scroll; Shift + up/down moves a page. In / Out moves between folder levels.','Press the right green load button for the preset, or the left green button for a device’s default. An amber button means the selected item is loaded; press it again to try the next entry.'
      ],[['Empty MIDI track','Browse available instruments, effects, sounds and plug-ins.'],['Preview','Core Library and official Pack items can include an audition preview.'],...(!two?[['Visible folders','Only folders with something loadable in the current context appear; samples become available when browsing a drum pad.']]:[])]),
      p(two?'setup-menu':'setting-user-preferences','Adjust the response','Open '+pref+' to tune pad response and workflow.',[],two?[
        ['Sensitivity','How easily a strike reaches high velocity.'],['Gain','Shifts the response curve, especially at medium strikes.'],['Dynamics','Spreads the result toward extremes or concentrates it near the middle.'],['Starting point','All three default to 5. For a linear curve, set Gain to 4 and Dynamics to 7.'],['Display / LEDs','Separate brightness settings. Very low LED brightness can alter perceived colors.'],
      ]:[
        ['Pad Threshold','The minimum force that triggers a note; too low can cause accidental or stuck notes.'],['Velocity Curve','Linear or logarithmic response; larger Log values give more range for soft playing.'],['Aftertouch Threshold','Ignores lower pressure values and expands values above the threshold to the full aftertouch range.']
      ],'',[
        {key:chapter+'#'+(two?'setup-menu':'setting-user-preferences'),label:'Choose Clip / Scene workflow',body:'The Workflow setting changes New, Duplicate and the up/down arrows.',steps:[],terms:[['Scene workflow','Duplicate captures currently playing clips into a new scene; New does that except for the selected track, which gets an empty slot. Up/down launches the next or previous scene.'],['Clip workflow','Duplicate and New affect only the selected track; other tracks continue. Shift + Duplicate captures a whole scene. Up/down launches only the selected track’s clip.']],images:[],keys:[],note:''}
      ]),
      p('using-footswitches-with-push-'+n,'Connect a pedal','Use momentary footswitches in the rear pedal sockets.',[],[['Socket 1','Sustain.'],['Socket 2','Tap to toggle recording/overdub/playback; double-tap for New.'],['Polarity','If the pedal works backward, use its polarity switch. Reconnecting while depressed can correct some pedals.']])
    ]);
    const play=p('playing-and-programming-beats','Play','Select a MIDI track and press Note. A Drum Rack uses drum layouts; another instrument uses pitched notes.',[],[], '',[
      detail('loop-selector','Divide the pads','The lower-left 4×4 plays drums, lower-right selects loop pages, and the upper four rows sequence the selected sound.',[
        ['Move bank','Use the touch strip or Octave buttons to move 16 drum pads; add Shift for one row.'],['Pad colors',two?'Track color: loaded; lighter: empty; white: selected; green: playing; blue: soloed; gray: muted.':'Yellow: loaded; dim yellow: empty; light blue: selected; green: playing; dark blue: soloed; orange: muted.'],['Alternate layout','Hold '+layout+' for temporary access; Shift + '+layout+' locks the alternate view.']
      ]),
      detail('16-velocities-mode','Choose a strike level','The lower-right 16 pads play the selected drum at 16 different velocities. Select a velocity there before placing a step.',[['Accent','Forces full velocity, overriding velocity-pad selection.']]),
      detail('64-pad-mode','Spread the kit','Cycle layouts with '+layout+' until all 64 pads play drums. Returning to the sequencer does not automatically change its selected 16-pad bank.'),
      p('loading-individual-drums','Replace one drum','Press Device, select a pad, then select that pad’s device entry before pressing Browse.',[
        two?'Tap the drum pad, then its second upper display button. Browse and Load a replacement; Load Next / Previous auditions nearby choices.':'Tap the drum pad, then the Selection button below its name. Browse to replace only that pad’s sound.',
        'Hold Select while pressing a pad to select it silently.'
      ],[], '',[detail('additional-pad-options-for-push-'+n,'Copy a pad','Hold Duplicate, tap the source, then the destination. This replaces destination devices, but does not replace notes already recorded for that pad.',two?[
        ['Pad parameters','On a selected pad, the first encoder changes choke group; the second transposes.'],['Color','Shift + pad opens the outer-ring color choices. These custom pad colors are saved in the Set but displayed only on Push.']
      ]:[])]),
      p('playing-melodies-and-harmonies','Play pitches','Add a MIDI track, load an instrument and press Note. The default grid is C major: right moves by scale step; up moves a fourth.',[],[['Root','Marked '+(two?'in the track color':'blue')+'. Other scale notes are white; held notes turn green or red while recording.'],['Range','Octave Up/Down changes the range.'],['Add track','A new track inserted while a group member is selected belongs to that group.']], '',[
        detail('playing-in-other-keys','Move the scale','Press '+(two?'Scale':'Scales')+' and choose a root and scale.',[['In Key / Chromatic','In Key offers only scale notes. Chromatic includes all notes, with out-of-scale notes unlit.'],['Fixed','Keeps note positions when changing key; off makes the lower-left pad the root. If Fixed is on and C is absent, the lowest pad uses the nearest scale note.'],['Layout','Choose thirds, fourths or sequential notes and vertical/horizontal orientation. '+(two?'Use Layout and Direction encoders.':'Hold Shift in Scales for layout choices.')],['Saved state','Root, scale and layout-related scale choices return with the Set.'],['Delete a pitch','Hold Delete and tap its pad to remove that pitch’s notes in the current loop.']])
      ])
    ]);
    const sequence=p('step-sequencing-beats','Sequence','Select a drum pad, then tap a step to add a note. Tap an occupied step to remove it; Mute + step disables it without deleting.',[],[['Grid','Scene/Grid buttons choose step size. With triplets, the rightmost two step columns are unavailable.'],['Select silently','Select + drum pad chooses the sound without playing.'],['Delete drum notes','Delete + pad removes that drum’s notes in the loop.'+(two?' If there are no recorded notes, it deletes the pad’s devices instead.':'')],['Playhead','Green while playing; red while recording.']], '',[
      detail('step-sequencing-melodies-and-harmonies','Place pitches in time','Press '+layout+' to reach the melodic sequencer. Rows are pitches; columns are steps. Octave controls and the strip move the pitch range.',[['In Key','Rows follow the selected scale; Chromatic makes other pitches available.'],['Range feedback','Bright strip lights show the visible notes; dim lights show other pitches with clip notes.']]),
      detail('adjusting-the-loop-length','Move / resize the loop','Hold one loop-page pad and tap another to span pages. Double-tap a page for a one-page loop.',[['View / loop','Tapping an in-loop page holds the editing view there without shortening the loop. Tapping outside the loop moves the loop there.'],['Follow','Reselect the loop to follow playback.'+(two?' Holding either Page button also restores follow.':'')],['Copy a page','Duplicate + source page, then destination adds notes; it does not clear the destination. Delete + page clears its notes.'],['Page length','Depends on step resolution and layout; a melodic page has eight steps.'],['Show page controls','Hold '+layout+'; Shift + '+layout+' locks them.']]),
      p('melodic-sequencer--32-notes','Sequence a chord','Use the bottom 32 pads to choose pitches and the top 32 to place them in time.',[],[], '',[
        detail('32-notes','Choose pitches','Play the lower pads, or use Select + pad to choose silently. Octave buttons move range; Shift + Octave moves by a scale note.'),
        detail('sequencer','Place / revise a step','Tap an upper step to insert all selected pitches. Hold a step to see its pitches below; tap one to remove it.',[['Several steps','Hold several steps to edit them together.'],['Copy','Duplicate + source step, then destination copies notes and their settings.'],['Loop pages','Hold '+layout+' to show page controls in row five.'],['Triplets','Only six pads per step row are active.']])
      ]),
      detail('note-specific-parameters','Nudge / resize / accent','In Clip mode, hold a step and turn the displayed Nudge, coarse/fine Length or Velocity encoder.',[['Several steps','Hold multiple step pads to adjust together; the display reports their value range.'],['Empty step','Holding an empty step and turning a note encoder can create a note with that setting.'],['One drum','Select + its drum pad applies these edits across that drum’s notes.'],['Nudge','Percentage offset from the preceding grid line; a negative value places it early.']])
    ]);
    const record=p('real-time-recording','Record','With Session focused, press Record, play the pads, then press Record again to keep the clip playing. Further presses toggle overdubbing.',[],[['Metronome','Turns the click on/off.'+(two?' Shift + Master adjusts its level; the display shows a configured count-in.':'')],['New','Stops the selected clip and prepares a fresh recording slot according to the Workflow setting.'],['Accent','Tap to latch full velocity; hold for temporary accent.']], '',[
      detail('fixed-length-recording','Set the length','Hold Fixed Length to choose bars, then enable it before recording.',[['Off','Recording continues until Record, New or Play/Stop ends it.'],['During recording','Enabling it closes recording and loops the last chosen number of bars.'],...(two?[['Phrase Sync','Begins at the corresponding position inside the fixed phrase. At song bar 7 with a four-bar phrase, recording starts at phrase bar 3.']]:[])]),
      p('additional-recording-options','Repeat / quantize','Repeat generates notes as you hold a pad; Quantize changes note timing after or during recording.',[],[], '',[
        detail('recording-with-repeat','Hold a rhythm','Enable Repeat and hold a pad. Scene/Grid sets the rate; pressure changes velocity and Swing shifts the repeated rhythm.',[['Momentary','Hold Repeat to use it only while held. Tap to latch.'],['Per track','The Repeat state and rate are remembered for each track.']]),
        detail('quantizing','Snap notes','Tap Quantize to apply it. Hold Quantize to set the grid, amount and swing; Quantize + drum pad affects only that drum.',[['Amount','Partial movement retains some original timing.'],['Record Quantize','Quantizes incoming notes automatically.'+(two?' Its automatic quantization does not apply the Swing setting.':'')],['Audio clip','Quantize targets transients rather than MIDI notes.']])
      ]),
      ...(two?[detail('arrangement-recording','Record the timeline','Record acts on the view focused in Live. Shift + Record targets the other view: Arrangement when Session is focused, and Session when Arrangement is focused.')]:[]),
      detail('recording-automation','Record a movement','Enable Automate / Automation and recording, then move an encoder. Turn automation recording off when finished.',[['Override','Manually changing an automated value overrides playback. Shift + Automate/Automation restores it.'],['Delete / reset','Delete + touch encoder removes its automation; without automation it resets the parameter.'],['Display',two?'White dot: automated; gray dot: overridden.':'Rectangle: automated; brackets around value: overridden.']]),
      detail('step-sequencing-automation','Set a step’s sound','In Device or '+(two?'Mix':'Volume')+' mode, hold one or more steps and turn a parameter encoder. It writes automation for that step’s time, even if the step has no note.'),
      ...(!two?[detail('per-step-automation','Limit the change','Hold only the steps whose device or mixer values should change. Releasing them returns the encoders to normal continuous control.')]:[])
    ]);
    const shape=p(two?'working-with-instruments-and-effects':'controlling-lives-instruments-and-effects','Shape / mix','Press Device and select a device to place its parameters on the encoders.',two?[
      'Select an upper display button for a device; press it again for Edit mode. The lower buttons select parameter pages.','Use the page arrows for devices with more than eight pages. The top-left button returns to the device-chain level.'
    ]:[
      'The Selection buttons choose devices; State buttons enable or disable them.','Use In / Out for further parameter banks or chains inside a Rack.'
    ],[['Fine adjustment','Hold Shift while turning an encoder.']], '',[
      ...(two?[
        detail('adding-deleting-and-reordering-devices','Add / move / remove','Add Device opens the Browser. Effects load beside the selected device; MIDI effects stay before the instrument and audio effects after it.',[['Instrument','Loading another instrument replaces the current one.'],['Move effect','Hold its upper display button and turn an encoder, then release at the destination.'],['Disable','Mute + upper display button; repeat to re-enable.'],['Delete','Delete + upper display button removes the device.']]),
        detail('working-with-racks','Enter a Rack','Select the Rack, then press its upper button again to unfold devices. Hold the Rack button to choose another chain with the lower buttons.',[['Macros','Encoders control Macros when the Rack itself is selected.'],['Drum Rack','Its device unfolding follows the state in Live rather than toggling directly on Push 2.']])
      ]:[]),
      detail(two?'track-control-and-mixing':'mixing-with-push-1','Mix',two?'Press Mix to alternate Track Mix and Global Mix. Select Mix or Input & Output in Track Mix.':'Use Volume for eight tracks; press Pan & Send to cycle pan and sends, or Track for volume, pan and six sends of one track.',[
        ['Track selection',two?'Lower display buttons choose tracks; arrows reveal others.':'Selection buttons choose tracks.'],['Main','The hardware Master button selects Live’s Main track.'],['Main / cue encoder','The far-right encoder controls Main level; Shift changes preview/cue level.'],['Split stereo pan','Use the single-track mixer to edit the two pan sliders; the global pan dial cannot edit them.'],...(two?[['More sends','Use display arrows when more than six returns exist.'],['I/O','Track Mix → Input & Output exposes routing and monitoring.']]:[['Groups','Hold a Group Track Selection button to fold or unfold it.']])
      ]),
      ...(two?[detail('rack-and-group-track-mixing','Enter a group','Press the selected group or Rack track’s lower display button again to unfold its tracks/chains. Arrows reveal items beyond the display.',[['Drum pad','Select + pad jumps to that pad in an unfolded Drum Rack mixer.']])]:[])
    ]);
    const launch=p('controlling-lives-session-view','Launch / move','Press Session: pads launch clips, and Scene/Grid buttons launch rows. Hold Session or Note for a temporary mode change.',[],[
      ['Select without launch','Select + clip pad; Select + scene button selects the row.'],['Record a slot','An empty slot on the armed track can record a new clip.'],['Stop one track',two?'Stop Clip stops the selected track; hold it and press another track’s lower button to stop that one.':'Enable Stop mode and press the track’s State button.'],['Stop all','Shift + '+(two?'Stop Clip':'Stop')+'.'],['Navigate','Arrows move a track or scene at a time. '+(two?'Page buttons move eight tracks; Octave moves eight scenes.':'Shift + arrows moves eight tracks or scenes; Octave also moves eight scenes.')],['Grid in Live','The colored outline shows which eight-by-eight region the hardware controls.'],['Clip colors',two?'Clips retain their color; playing clips pulse, recording clips pulse red. Shift + clip pad opens color choices.':'Stopped clips retain their color; playing clips pulse green/white and recording clips red/white.']
    ], '',[
      detail('session-overview','Zoom out',two?'Hold Layout to see 8×8 blocks. Shift + Layout latches the overview; Layout returns.':'Hold Shift to see the Session in 8×8 blocks.',[['Select a block','Tap a pad to move the controlled grid there. A scene button chooses a 64-scene block.'],['Colors',two?'White: selected block; green: playing clips; unlit: outside the Set.':'Amber: selected block; green: playing clips; red: no playing clips; unlit: outside the Set.']]),
      detail('navigating-in-note-mode','Move to another track','Left/right chooses a track. Selecting a MIDI track automatically arms it; Live shows this implicit arm in pink.',[['Up / down','Launches according to Clip/Scene workflow and takes over the current play position, like legato launching. It is not silent browsing.'],...(two?[['Manual arm','Hold a track’s lower display button, or Record + that button. Live shows a manually armed track in red.']]:[])])
    ]);
    // Put the hardware reference beside the actions it controls, not in a second index.
    if(!two){
      connect.details.push(detail('push-1-control-reference','Read the panel','Mode buttons change what the pads, display buttons and encoders do. Hold many mode buttons for a temporary change; release to return.'));
      const assignments=[
        [launch,'focusnavigation-section','Select / navigate','Note plays or sequences; Session launches. Arrows move the active region; Select chooses a clip or drum without triggering it.'],
        [connect,'add-section','Add a track / effect','Add Track inserts MIDI; hold it to choose Audio or Return. Add Effect inserts after the selected device; Shift inserts before. Select the instrument and Shift + Add Effect to insert a MIDI effect.'],
        [play,'note-section','Accent / change octave','Accent forces full velocity. Scales affects pitched instruments, not Drum Racks. Octave shifts pitched notes, drum banks, or eight Session scenes according to mode. User disables the standard mapping; relative encoders use Relative (2’s Comp.) for manual assignments.'],
        [launch,'state-control-section','Stop / mute / solo','Stop, Mute or Solo chooses what the eight State buttons do to tracks. In Device mode the same buttons enable devices. Shift + Stop stops all clips.'],
        [shape,'selection-control-section','Choose a target','Selection buttons choose the track or device represented above. In / Out enters Rack chains or more parameter banks; in Browse it moves between folders.'],
        [shape,'displayencoder-section','Edit a clip','Clip mode assigns the encoders to start/loop position, length/end and Loop on/off. Audio clips also offer Warp mode, detune, transpose and gain.'],
        [record,'tempo-section','Tap / swing','Tap the pulse with Tap Tempo; with Start Playback with Tap Tempo enabled, a bar of taps starts playback. Tempo encoder changes 1 BPM, or 0.1 with Shift. The Swing encoder affects Repeat and quantization.'],
        [sequence,'edit-section','Undo / double','Undo reverses the last Live edit, including mouse edits; Shift + Undo redoes. Double doubles both loop material and length. Delete acts on the current clip; hold it with a target to remove that clip, device, track or automation.'],
        [record,'transport-section','Start / capture','Play/Stop controls transport. Shift + Play/Stop returns to 1.1.1 without starting. Record + New captures recent MIDI on an armed MIDI track. Delete + Automation clears the clip’s automation.'],
        [play,'touch-strip','Bend / modulate','While playing an instrument, Select + tap strip toggles pitch bend and mod wheel. In a sequencer it moves pitch range; with drums it changes banks.'],
        [play,'pad-section','Read the mode','Session pads address clip slots. Note pads address pitches, drum sounds or sequencer steps according to track type and layout.'],
        [sequence,'scenegrid-section','Choose a grid / scene','In Note mode, Scene/Grid sets step and Repeat resolution. In Session it launches scenes; Select + scene chooses without launching.']
      ];
      for(const [parent,...row]of assignments)parent.details.push(detail(...row));
    }else{
      connect.details.push(detail('push-2-control-reference','Use the panel','Mode buttons change the encoders and pad grid. Hold Device, Mix or Clip temporarily; release to return.',[
        ['Undo / redo','Undo reverses the last edit in Live, not just hardware edits. Shift + Undo redoes.'],['Delete','Targets the current clip; hold with a track, device, pad or encoder to remove that target or its automation. Without automation, Delete + encoder resets its value.'],['Double Loop','Doubles both notes and loop length.'],['Duplicate','Hold with a track button to copy the track, or in Session copy a clip to another slot.'],['Tap / tempo','Tap Tempo estimates BPM; the Tempo encoder adjusts 1 BPM or 0.1 with Shift.'],['Mute / Solo','Hold with a track button, drum pad or device to target it. Holding Mute, Solo or Stop Clip can latch that mode; press again to release.'],['User','Disables the standard Live mapping. For manual relative-encoder mappings, use Relative (2’s Comp.).'],['Touch strip','Select + tap toggles bend/mod-wheel in real-time pitched playing; sequencing moves pitch range and drums move banks.'],['Play/Stop','While stopped, Shift + Play/Stop returns to 1.1.1 without starting.'],['Convert','A Classic/One-Shot Simpler becomes a new Drum Rack track; sliced Simpler becomes a Drum Rack on the same track. A drum pad can be extracted to a new MIDI track. An audio clip can become Simpler/Drum Rack or use Harmony/Melody/Drums-to-MIDI.']
      ]));
      sequence.details.push(p('clip-mode','Frame the clip','Press Clip. With Loop on, adjust Loop Position, Loop Length and Start Offset; with Loop off, adjust Start and End.',[],[['Fine movement','Shift adjusts positions in sixteenths.'],['Zoom','The first encoder zooms around the most recently touched position control.'],['Audio','Also adjust Warp mode, gain and transpose; Shift + Transpose adjusts cents.']], '',[
        detail('using-midi-tracks-in-clip-mode','Crop MIDI','Crop deletes material outside the selected loop. The display’s layout follows the chosen pad layout.'),
        detail('real-time-playing-layouts','See incoming notes','The 64-note, 64-pad and 64-slice layouts fit all clip notes on the display, including incoming external MIDI.'),
        detail('sequencing-layouts','Locate the editable page','The translucent box marks the time/pitch area controlled by the pads. Marks at the left show other pitch ranges with notes; denser ranges have thicker marks.'),
        detail('melodic-sequencer','Move the page','A melodic-sequencer page spans eight pitches. Loop pads or Page left/right moves time; Octave or the strip moves pitch.'),
        detail('melodic-sequencer--32-notes-1','Find the chosen pitches','In the 32-notes layout the display fits all notes, then highlights the selected pitches’ editable area. In drum/slice layouts it shows the selected pad only.')
      ]));
    }
    return {family:'settings',id:'push-'+n,label:'Push '+n,items:[connect,play,sequence,record,shape,launch]};
  }
  function samples(){
    const p=manualCompletion.make('using-push-2');
    return {family:'settings',id:'push-2-samples',label:'Push 2 · Samples',items:[
      p('working-with-samples','Load','Load a sample onto a MIDI track to play it through Simpler. Device mode shows the waveform.',[
        'Choose Classic, One-Shot or Slicing with the Mode encoder.','Check Warp and loop settings: Simpler chooses initial behavior from sample length; an empty Simpler makes no sound.'
      ],[['Getting a sample','Add a MIDI track, or press Browse on an existing one.'],['Defaults from length','Short samples play once; long ones loop and warp.'],['From a warped clip','The sample retains its Warp settings and markers.'],['Warp on','Plays at the Set tempo whichever note you play.'],['Classic Playback Mode','Default: polyphonic, full ADSR, loops while a note is held; pitched pad layout.'],['One-Shot Playback Mode','Monophonic, simplified envelope, no looping; plays the whole sample however long the pad is held.'],['Slicing Playback Mode','Cuts the sample non-destructively into slices on the pads, manually or automatically; suits drum breaks.']]),
      p('classic-playback-mode','Loop / sustain','Classic supports polyphony, an ADSR envelope and a sustain loop.',[
        'Set Start and End to bound the usable sample region. Adjust S Start and S Length inside that region.','Enable Loop and set S Loop Length. Zoom follows the last touched position control.','Press Simpler’s upper display button for Edit; lower buttons choose parameter pages.'
      ],[['Relative lengths','S Start, S Length and S Loop Length are percentages of the Start–End region.'],['Warp as…','Fits that region into the chosen bars; ÷2 / ×2 correct a double/half-time interpretation.'],['Crop / Reverse','Create a processed copy; the original file is retained.']]),
      p('one-shot-mode','Trigger / gate','One-Shot plays one voice without looping.',[],[['Trigger','Releasing the pad does not stop the sample. Fade Out applies near the region end.'],['Gate','Release begins the Fade Out.'],['Fade In','Time to reach full level after triggering.'],['Transpose','Up to ±48 semitones; Warp mode affects the result.'],['Gain','Sets Simpler’s output level.'],['Stop immediately','Shift + Play/Stop silences the one-shot.']]),
      p('legato-playback','Repitch without restarting','In Edit → Global, choose Glide. In Classic, also set Voices to 1; One-Shot is already monophonic.',[
        'Overlap played notes to change pitch without restarting the sample.','Enable Warp if duration should stay steady; compare Warp modes for the particular sample.'
      ]),
      p('slicing-mode','Slice / rearrange','Choose how to divide the sample, then play its slices on the pads.',[],[['Transient','Sensitivity sets the detected transient count, up to 64 slices.'],['Beat','Division sets musical beat spacing.'],['Region','Regions sets equal time divisions.'],['Manual','Enable Pad Slicing, start an existing slice, and tap empty pads at new cut points. Turn Pad Slicing off when finished.'],['Order','Slices fill bottom-left groups of four upward, then the right half.'],['Playback','Mono: one slice; Poly: overlapping slices; Through: one voice continues through the remaining sample.'],['Trigger / Gate','Release behavior works with the chosen playback mode.'],['Nudge','Select a slice and adjust its boundary; Zoom and Shift allow finer work.'],['Split Slice','Inserts a cut halfway through the selected slice.'],['Delete','Delete + slice pad removes its marker.'],['Layout','Cycle 64-pad, Loop Selector and 16 Velocities with Layout.']])
    ]};
  }
  return {areas:()=>[controller(1),controller(2),samples()]};
})();
